name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JUnit Tests
          path: '*.xml'
          reporter: java-junit